name: Build, Bundle, Release Go Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.19' # The Go version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: ${{ env.GO_VERSION}}

    - name: Build Go Plugin
      run: |
        cd src/custom-go-plugin
        docker compose run --rm tyk-plugin-compiler RateLimitingPlugin.so
        mv -f ./go/src/RateLimitingPlugin*.so ./tyk/middleware/RateLimitingPlugin.so

    - name: Install go-coverage-report
      run: go install github.com/ncruces/go-coverage-report@latest

    - name: Generate Coverage Report
      run: go-coverage-report -format=html -path=coverage.html ./...

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v2
      with:
       name: coverage-report
       path: coverage.html

    - name: Post Comment with Coverage Report
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Test Coverage Report:
          [View Coverage Report](https://github.com/irving-zamora/GithubActionsTest/blob/${{ github.sha }}/coverage.html)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Tests and Generate Coverage
      run: |
        cd ./src/custom-go-plugin/go/src/
        go test -v -coverprofile=coverage.txt ./...
        go tool cover -func=coverage.txt > coverage_summary.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-coverage
        path: |
          coverage.txt
          coverage.html

    - name: Display Test Results
      uses: actions/upload-artifact@v2
      with:
       name: test-results
       path: coverage.out

    - name: Comment on Pull Request
      uses: marocchino/sticky-pull-request-comment@v2
      with:
          message: |
            Test Results:

            ```plaintext
            $(cat coverage.txt)
            ```

            Coverage Report: [Coverage Report](https://github.com/irving-zamora/GithubActionsTest/src/custom-go-plugin/go/src/coverage.html)            
