name: Build, Bundle, Release Go Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.19' # The Go version to use

permissions:
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: ${{ env.GO_VERSION}}

    - name: Build Go Plugin
      run: |
        cd src/custom-go-plugin
        docker compose run --rm tyk-plugin-compiler RateLimitingPlugin.so
        mv -f ./go/src/RateLimitingPlugin*.so ./tyk/middleware/RateLimitingPlugin.so

    - name: Run Tests and Generate Coverage
      continue-on-error: true
      run: |
        cd ./src/custom-go-plugin/go/src/
        go test -v -coverprofile=coverage.txt ./...
        go tool cover -func=coverage.txt > coverage_summary.txt
        
    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-coverage
        path: |
          /home/runner/work/GithubActionsTest/GithubActionsTest/src/custom-go-plugin/go/src/coverage.txt
          /home/runner/work/GithubActionsTest/GithubActionsTest/src/custom-go-plugin/go/src/coverage.html

    - name: Display Test Results
      uses: actions/upload-artifact@v2
      with:
       name: test-results
       path: |
         artifact:test-results/coverage.txt
         artifact:test-results/coverage.html

    - name: Comment on Pull Request
      uses: marocchino/sticky-pull-request-comment@v2
      with:
          message: |
            Test Results:

            ```plaintext
            $(cat artifact:test-results/coverage.html)
            ```
            [View Function-Level Coverage Report](artifact:coverage-func.html)
            Coverage Report: [Coverage Report](/home/runner/work/GithubActionsTest/GithubActionsTest/src/custom-go-plugin/go/src/coverage.html)
    
    - name: Generate Function-Level Coverage Report
      run: go get -u github.com/ncruces/go-coverage-report
    - run: go-coverage-report -o coverage-func.html -f html -i coverage.txt

    - name: Comment on Pull Request with Coverage Report
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Test Results:

          [View Function-Level Coverage Report](artifact:coverage-func.html)

    - name: Upload Coverage Function-Level Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-func
        path: coverage-func.html

    - name: Comment on Pull Request with Coverage Report
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Coverage Report: [View Coverage Report](artifact:test-coverage/coverage.html)
           - [Coverage Text Report](artifact:test-coverage/coverage.txt)
           - [Coverage HTML Report](artifact:test-coverage/coverage.html)